# Website URLs
topjobs.url=https://www.topjobs.lk/applicant/vacancybyfunctionalarea.jsp?FA=SDQ&jst=OPEN
itpro.api.url=https://itpro.lk/api
rooster.url=https://rooster.jobs/jobs

# notifier related
telegram.api.url=https://api.telegram.org/bot%s/sendMessage?chat_id=%s&text=%s&parse_mode=Markdown

# Scraping Settings
max.days.old=14
request.delay.ms=2000

# Job Filtering Keywords
tech.keywords=software,full-stack,fullstack,full stack,frontend,backend,web,dev,mobile,programmer,React,developer,AI
techjobs.keywords=intern,associate,trainee,senior,lead,junior,mid,engineer