name: Automated Job Scraper
on:
  schedule:
    - cron: '30 5 * * *'
    - cron: '30 11 * * *'
  workflow_dispatch:

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build and Run Scraper
        run: mvn clean compile exec:java -Dexec.mainClass="lk.jobs.engine.ScraperManager"
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

      - name: Commit and Push Changes
        run: |
          git config --global user.name "Senadeera-NK"
          git config --global user.email "nanduniofficial@gmail.com"
          git add .
          # Only commit if there are changes to avoid workflow errors
          git diff --quiet && git diff --staged --quiet || (git commit -m "Auto-update jobs: $(date)" && git push)
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}